### ISSUE TITLE
Error 503. Steam deprecation of GetPlayerSummaries API endpoint

### ISSUE THREAD

**Issue by saskenuba** [byo-software/steam-openid-connect-provider#20]
Out of nowhere, Steam has deprecated the GetPlayerSummaries API endpoint as you can check here: 
https://partner.steamgames.com/doc/webapi/ISteamUser#GetPlayerSummaries

So the server crashes after a successful credentials exchange just before returning the user's profile.
Can `steam-openid-connect-provider` return only the user SteamID and make no API calls?

**Comment by Trojaner** [comment]
It's been over a year and a half since this issue has been initially reported and nothing similar happened again since then.
The Steam Web API on the Valve Developer Community Wiki also still lists this as a public non-deprecated API:
https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerSummaries_.28v0002.29

Only the older v1 version is deprecated (and prob. even removed) but we already only use v2.
Hence, closing for now.
